In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("quick_view.csv")
df.head()

,Ticker,Name,Sector,P/E,P/B,PEG,D/E,ROIC,Dividend Yield %,1M %,1Y %,Peter Lynch,Personal Model
0,AAPL,Apple Inc.,Technology,38.92,57.79,2.46,1.54,0.78,0.00,12.43,13.07,0.81,75.0
1,AMZN,"Amazon.com, Inc.",Consumer Cyclical,34.70,7.27,2.02,0.48,0.22,0.00,-0.53,17.41,0.99,100.0
2,NVDA,NVIDIA Corporation,Technology,52.31,44.64,1.37,0.11,0.93,0.00,3.16,57.93,1.46,87.5
3,MSFT,Microsoft Corporation,Technology,37.74,11.13,2.25,0.33,0.33,0.01,1.42,18.67,0.89,100.0
4,META,"Meta Platforms, Inc.",Communication Services,27.77,9.87,2.09,0.25,0.36,0.00,1.37,35.57,0.96,100.0

In [9]:
df_tech = df[df["Sector"]=="Technology"]
df_tech.describe()

,P/E,P/B,PEG,D/E,ROIC,Dividend Yield %,1M %,1Y %,Peter Lynch,Personal Model
count,134.000000,150.000000,98.000000,150.000000,143.000000,150.000000,148.000000,148.00000,150.00000,150.000000
mean,61.868060,27.934067,2.153265,0.651333,0.145315,0.007933,7.035878,26.11723,0.97580,59.500000
std,106.703741,144.491222,1.766770,1.091466,0.561118,0.010510,13.013140,59.70363,1.43692,24.733479
min,8.390000,-107.670000,0.180000,0.000000,-5.370000,0.000000,-15.120000,-82.42000,0.00000,12.500000
25%,23.957500,3.152500,1.122500,0.060000,0.070000,0.000000,-0.992500,-4.61500,0.00000,50.000000
50%,33.280000,6.180000,1.855000,0.310000,0.140000,0.000000,4.045000,12.75000,0.75500,62.500000
75%,57.042500,13.287500,2.467500,0.800000,0.220000,0.010000,12.017500,40.37500,1.27000,75.000000
max,956.270000,1348.650000,13.000000,9.600000,3.240000,0.040000,50.610000,425.83000,11.25000,100.000000

In [11]:
df_health = df[df["Sector"]=="Healthcare"]
df_health.describe()

,P/E,P/B,PEG,D/E,ROIC,Dividend Yield %,1M %,1Y %,Peter Lynch,Personal Model
count,104.000000,111.000000,73.000000,111.000000,97.000000,111.000000,111.000000,111.000000,111.000000,111.000000
mean,37.454615,-2.553874,1.686986,0.895405,0.032474,0.011982,42.629550,-1.816396,1.335225,59.121622
std,56.577836,214.385048,1.290122,1.611580,1.144679,0.015065,465.285359,34.237133,1.993384,23.168475
min,3.120000,-2140.290000,0.130000,0.000000,-11.040000,0.000000,-19.470000,-96.000000,0.000000,0.000000
25%,17.145000,1.710000,0.890000,0.115000,0.080000,0.000000,-6.520000,-21.970000,0.000000,50.000000
50%,25.230000,3.550000,1.270000,0.590000,0.120000,0.010000,-1.300000,-9.100000,0.950000,62.500000
75%,36.452500,7.230000,1.970000,0.845000,0.200000,0.020000,2.340000,15.175000,1.920000,75.000000
max,502.500000,411.690000,7.570000,10.930000,0.790000,0.070000,4900.000000,151.960000,15.840000,100.000000

In [13]:
df_comm = df[df["Sector"]=="Communication Services"]
df_comm.describe()

,P/E,P/B,PEG,D/E,ROIC,Dividend Yield %,1M %,1Y %,Peter Lynch,Personal Model
count,48.000000,56.000000,32.000000,56.000000,45.000000,56.000000,56.000000,56.000000,56.000000,56.000000
mean,38.628542,46.092321,4.292500,1.057500,0.103111,0.017321,1.538571,35.563929,0.605357,52.232143
std,35.008066,166.969363,5.623094,1.117037,0.202763,0.024457,13.755658,76.461612,0.837112,25.794990
min,5.220000,0.900000,0.390000,0.000000,-0.670000,0.000000,-13.250000,-57.480000,0.000000,12.500000
25%,16.830000,2.227500,1.367500,0.227500,0.050000,0.000000,-6.300000,0.717500,0.000000,37.500000
50%,26.615000,4.055000,2.020000,0.840000,0.110000,0.010000,-2.835000,19.520000,0.135000,50.000000
75%,46.747500,8.790000,3.317500,1.482500,0.180000,0.032500,2.147500,49.050000,1.010000,75.000000
max,163.750000,1197.530000,24.650000,5.290000,0.590000,0.110000,62.740000,410.230000,3.810000,100.000000

In [14]:
df_cons = df[df["Sector"]=="Consumer Cyclical"]
df_cons.describe()

,P/E,P/B,PEG,D/E,ROIC,Dividend Yield %,1M %,1Y %,Peter Lynch,Personal Model
count,107.000000,113.000000,72.000000,113.000000,95.000000,113.000000,113.000000,113.000000,113.000000,113.000000
mean,35.397850,22.063717,2.208056,1.283805,0.216842,0.014956,-0.770265,11.510619,1.047965,55.420354
std,41.630885,118.283900,2.114606,1.612979,0.208517,0.015418,8.342151,32.076190,1.639680,23.674463
min,6.770000,-517.730000,0.160000,0.000000,-0.300000,0.000000,-32.800000,-47.700000,0.000000,0.000000
25%,18.235000,1.240000,1.057500,0.250000,0.080000,0.000000,-4.250000,-8.300000,0.000000,37.500000
50%,24.440000,4.400000,1.765000,0.830000,0.150000,0.010000,-1.270000,5.110000,0.720000,62.500000
75%,36.030000,11.410000,2.610000,1.580000,0.310000,0.020000,2.000000,25.470000,1.360000,75.000000
max,270.110000,827.250000,14.290000,7.770000,0.960000,0.060000,49.920000,125.610000,12.730000,100.000000

In [15]:
df_fin = df[df["Sector"]=="Financial Services"]
df_fin.describe()

,P/E,P/B,PEG,D/E,ROIC,Dividend Yield %,1M %,1Y %,Peter Lynch,Personal Model
count,172.000000,177.000000,79.000000,177.000000,69.000000,177.000000,177.000000,177.000000,177.000000,177.000000
mean,26.157267,23.695480,3.158354,0.675424,0.185797,0.023785,-0.833672,25.596045,2.201299,48.234463
std,52.677402,92.625718,6.126764,1.587226,0.215805,0.019593,5.283146,42.168148,22.081085,19.707307
min,7.590000,-206.300000,0.010000,0.000000,0.010000,0.000000,-22.530000,-40.360000,0.000000,0.000000
25%,12.270000,1.310000,1.285000,0.000000,0.090000,0.010000,-3.980000,5.120000,0.000000,37.500000
50%,15.260000,2.110000,1.980000,0.220000,0.150000,0.020000,-1.180000,18.190000,0.000000,50.000000
75%,23.720000,4.620000,2.650000,0.600000,0.200000,0.030000,2.020000,41.170000,1.000000,62.500000
max,626.140000,725.380000,53.400000,11.970000,1.700000,0.120000,14.240000,450.180000,294.120000,100.000000